iotaledger/legacy-migration-tool

packages/desktop/App.svelte, packages/mobile/App.svelte, packages/shared/components/inputs/Dropzone.svelte, packages/shared/lib/appSettings.ts, packages/shared/lib/core/router/app-router.ts, packages/shared/lib/profile.ts, packages/shared/locales/en.json, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/CrashReporting.svelte, packages/shared/routes/setup/Profile.svelte, packages/shared/routes/setup/Setup.svelte, packages/shared/routes/setup/Welcome.svelte, packages/shared/routes/setup/import/views/FileImport.svelte, packages/shared/routes/setup/import/views/Import.svelte, packages/shared/routes/setup/import/views/Ledger.svelte, packages/shared/routes/setup/import/views/TextImport.svelte, packages/shared/routes/setup/legal/Legal.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
```
- Remove code from the onboarding that isn't necessary for migration.
- Remove the locales since the tool will only be available in English
```
Closes #5 
- __Desktop__
- __Mobile__
=> feat:  Update onboarding to be migration only

packages/shared/lib/migration.ts, packages/shared/lib/utils.ts, packages/shared/package.json, yarn.lock
Closes #39 
Use iotajs to generate legacy addresses from a legacy seed
```
Use iotajs to generate legacy addresses from a legacy seed.
```
- __Desktop__
=> feat: use iotajs to generate legacy addresses from a legacy seed

packages/shared/lib/migration.ts
=> Chore: Update chainId

packages/shared/lib/migration.ts
=> Fix: Last checked address index

packages/shared/lib/core/router/app-router.ts
Skip setting pin step from the migration flow
Resolves #20 
- __Desktop__
=> feat: remove set pin route

packages/shared/lib/migration.ts
Closes #42
```
```
- __Desktop__
=> feat: update getLedgerMigrationData

packages/shared/components/SpentAddress.svelte, packages/shared/components/TransactionItem.svelte, packages/shared/components/inputs/Amount.svelte, packages/shared/components/popups/Transaction.svelte, packages/shared/lib/app.ts, packages/shared/lib/assets.ts, packages/shared/lib/chart.ts, packages/shared/lib/typings/sendParams.ts, packages/shared/lib/units.ts, packages/shared/lib/wallet.ts, packages/shared/lib/walletApiListeners.ts, packages/shared/package.json, packages/shared/routes/setup/Balance.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte, yarn.lock
Closes #34 
Remove metric system, display migration balances in new unit format
```
- Remove metric system
- Display migration balances in new unit format
```
- __Desktop__
=> feat: remove metric system

packages/shared/lib/migration.ts, packages/shared/routes/setup/migrate/views/Migrate.svelte
- Add submitting migration bundle as off ledger request to wasp node
- Add polling wasp node for receipt
Resolves #57 
```
```
- __Desktop__
=> Feat: Add offledger request for ledger devices

packages/shared/lib/migration.ts, packages/shared/routes/setup/Balance.svelte
For **_Software Profiles_** allow sending migration request with any amount and let the contract decide what is migrate-able
Resolves #43 
Note: We can create a new task and PR for Ledger Devices
- __Desktop__
=> Fix: Minimum migratable amount

packages/shared/lib/migration.ts, packages/shared/routes/setup/Balance.svelte
Fix Check Again functionality to search for balances on ledger devices 
Resolves #58 
- __Desktop__
=> Fix: Search for balances on ledger devices

packages/shared/lib/migration.ts, packages/shared/locales/en.json, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte
Closes #61
The explorer link of the congratulations view does not open correctly
```
```
- __Desktop__
=> feat: continue with the flow of migration

packages/desktop/electron/main.js, packages/shared/routes/setup/Congratulations.svelte
Closes #68
Add explorer urls to externalAllowlist
```
Add explorer urls to externalAllowlist
```
- __Desktop__
=> fix: add explorer urls to externalAllowlist

packages/desktop/electron/electronApi.js, packages/shared/lib/tests/mocks/platform.ts, packages/shared/lib/typings/platform.ts, packages/shared/routes/setup/Congratulations.svelte
Closes #67
Export the migration file with the information of the store object
```
- Export the migration file with the information of the store object
- Unify the same `migration log` function method for `ledger` and `software` profiles
```
- __Desktop__
=> fix: migrate log for software profiles

packages/shared/routes/setup/migrate/views/Migrate.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Routing to Congratulations page after bundle migration and error handling 
```
```
- __Desktop__
=> Fix: Migration flow routing and error handling

packages/shared/lib/migration.ts
=> feat: update chain id

packages/shared/lib/migration.ts, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Closes #82
Continue to the congrats view if some transaction has migrated he funds successfully
```
```
- __Desktop__
=> fix: continue to the congrats view

packages/shared/lib/migration.ts
Closes #85 
```
```
- __Desktop__
=> fix: migrate funds sent to first profile

packages/shared/lib/core/router/subrouters/import-router.ts, packages/shared/locales/en.json
Remove mentions of Firefly
resolves #84 
- __Desktop__
=> Fix: Update strings

packages/shared/routes/setup/ledger/views/SwitchApps.svelte
Closes #81
```
```
- __Desktop__
=> fix: displayNotificationForLedgerProfile to not ignore detected ledger

packages/shared/lib/migration.ts, packages/shared/lib/typings/migration.ts, packages/shared/routes/setup/migrate/views/Migrate.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Closes #86
```
```
- __Desktop__
=> feat: add more info into migration logs

packages/shared/lib/migration.ts, packages/shared/routes/setup/migrate/views/Migrate.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Closes #96
```
```
- __Desktop__
=> fix: total migration balance

packages/shared/components/popups/LedgerLegacyTransaction.svelte, packages/shared/lib/migration.ts
Increased amount of the input with the smallest balance when migration amount is less than min migratable amount 
Resolves #93 
```
```
- __Desktop__
=> Fix: Adjust balance for the inputs when creating the bundle

.github/workflows/build-desktop.yml, packages/desktop/package.json
Closes #104
[alpha-release](https://github.com/iotaledger/legacy-migration-tool/actions/runs/7297733654)
[beta-release](https://github.com/iotaledger/legacy-migration-tool/actions/runs/7297741620)
[production-release](https://github.com/iotaledger/legacy-migration-tool/actions/runs/7298649427)
```
```
- __Desktop__
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your …
=> feat: modify CI

packages/shared/lib/errors.ts, packages/shared/lib/migration.ts, packages/shared/lib/typings/migration.ts, packages/shared/routes/setup/Balance.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Closes #91
```
```
- __Desktop__
=> feat: improve migration log file when tracking an error

packages/shared/components/popups/LedgerConnectionGuide.svelte, packages/shared/components/popups/MissingBundle.svelte, packages/shared/locales/en.json, packages/shared/routes/setup/ledger/views/LegacyIntro.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte
Closes #99
```
```
- __Desktop__
=> feat: check links

packages/shared/lib/network.ts
Closes #108
```
```
- __Desktop__
=> fix: update client options to avoid using chrysalis nodes

packages/desktop/public/index.html, packages/shared/components/OnboardingLayout.svelte, packages/shared/lib/migration.ts, packages/shared/locales/en.json, packages/shared/routes/setup/ledger/views/LegacyIntro.svelte
Closes #13
```
```
- __Desktop__
=> feat: remove tutorial videos

packages/shared/lib/network.ts, packages/shared/lib/tests/network.test.ts
Closes #112
```
```
- __Desktop__
=> fix: client options in ledger profiles

packages/shared/routes/setup/migrate/views/Migrate.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
- added logs for canceled transaction
- improve notifications for ledger devices to display ledger event error messages and migration error messages
resolves #115 
- __Desktop__
=> Fix: Improve Ledger logs and notifications

packages/shared/routes/setup/migrate/views/Migrate.svelte
Fix displaying ledger device error notification
- __Desktop__
- Test by migrating single bundle with amount less than Stardust minimum required storage deposit
=> Fix: Ledger device error notification

packages/shared/lib/app.ts, packages/shared/lib/core/router/app-router.ts, packages/shared/routes/setup/legal/Content.svelte, packages/shared/routes/setup/legal/Legal.svelte
Close https://github.com/iotaledger/legacy-migration-tool/issues/6
=> copy: update legal text

packages/shared/lib/migration.ts, packages/shared/lib/network.ts, packages/shared/routes/setup/Balance.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/Welcome.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Close https://github.com/iotaledger/legacy-migration-tool/issues/121
=> chore: code improvements low severity

packages/shared/routes/setup/migrate/views/Migrate.svelte
Closes #98
```
```
- __Desktop__
=> feat: add new migration link

packages/desktop/package.json
=> chore: bump version to `1.0.0-beta-1`

packages/desktop/electron/lib/menu.js
Add context menu for right click
Close https://github.com/iotaledger/legacy-migration-tool/issues/129
- __Desktop__
=> Fix: Add Context menu

.github/workflows/build-desktop.yml
=> hotfix: broken release CI

packages/desktop/public/index.html, packages/shared/lib/migration.ts
=> chore: update production migrator api and chain id
